default: &default
  adapter: postgresql
  encoding: unicode

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: rails
  password: root
  

development:
  <<: *default
  database: goxperia_development

test:
  <<: *default
  database: goxperia_test


production:
  <<: *default
  database: goxperia_development
  username: salman
  password: root
