default: &default
  adapter: postgresql
  encoding: unicode

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: 320ee6509fffd3bb58091ad25ce084e2
  password: root
  

development:
  <<: *default
  database: goxperia_development

test:
  <<: *default
  database: goxperia_test


production:
  <<: *default
  database: goxperia_development
  username: salman
  password: <%= ENV["SECRET_KEY_BASE"] %>

