location1 = Location.create(
  company_name: 'Breakout',
  name: 'Breakout Atlanta',
  city: 'Atlanta',
  state: 'GA',
  zip: 30342,
  address: '3867 Roswell Rd, Ste 200',
  phone: '555-555-5555',
  email: 'name@example.com',
  website: 'http://www.google.com',
  category: 1,
  description: 'A description',
)
location2 = Location.create(
  company_name: 'Escape Hunt',
  name: 'Escape Hunt Minneapolis',
  city: 'Minneapolis',
  state: 'MN',
  zip: 55401,
  address: '123 Washington Ave',
  phone: '555-555-5555',
  email: 'name@example.com',
  website: 'http://www.google.com',
  category: 1,
  description: 'A description',
)
location3 = Location.create(
  id: 3,
  company_name: 'The Room',
  name: 'The Room Denver',
  city: 'Denver',
  state: 'CO',
  zip: 80231,
  address: '10200 East Girard Ave #B400',
  phone: '555-555-5555',
  email: 'name@example.com',
  website: 'http://www.google.com',
  category: 3,
  description: 'A description',
)
location4 = Location.create(
  id: 4,
  company_name: 'Breakout Games',
  name: 'Los Angeles',
  city: 'Anaheim',
  state: 'CA',
  zip: 92802,
  address: '400 Disney Way #313',
  phone: '555-555-5555',
  email: 'name@example.com',
  website: 'http://www.google.com',
  category: 4,
  description: 'A description',
)